- name: resource manager acls

  hosts: all

  gather_facts: False
  become: True
  connection: ansible.netcommon.network_cli

  vars:
    test_change: False

  tasks:
    - name: get acls from running-config
      mwallraf.ekinops.oneos_acls:
        config:
        state: gathered
      register: gathered_acls

    # - name: parse interface acl
    #   mwallraf.ekinops.oneos_acl_interfaces:
    #     running_config: |
    #       interface GigabitEthernet 0/3
    #       ip access-group TEST1 in
    #       ip access-group TEST1 out
    #       exit
    #     state: parsed
    #   register: parsed_acl

    # - name: render interface acl
    #   mwallraf.ekinops.oneos_acl_interfaces:
    #     config:
    #       - name: Gig 5/0
    #         access_groups:
    #           - afi: ipv4
    #             acls:
    #               - name: 110
    #                 direction: in
    #               - name: TESTTEST
    #                 direction: out
    #     state: rendered
    #   register: rendered_acl

    # - name: remove interface acl
    #   mwallraf.ekinops.oneos_acl_interfaces:
    #     config:
    #       - name: GigabitEthernet 0/3
    #       - name: blablaBla
    #     state: deleted
    #   register: deleted_acl

    # - name: replace interface acl
    #   mwallraf.ekinops.oneos_acl_interfaces:
    #     config:
    #       - name: GigabitEthernet 0/3
    #         access_groups:
    #           - afi: ipv4
    #             acls:
    #               - name: TEST1
    #                 direction: out
    #     state: replaced
    #   register: replaced_acl

    # - name: merge interface acl
    #   mwallraf.ekinops.oneos_acl_interfaces:
    #     config:
    #       - name: GigabitEthernet 0/3
    #         access_groups:
    #           - afi: ipv4
    #             acls:
    #               - name: TEST1
    #                 direction: in
    #     state: merged
    #   register: merged_acl

    # - name: cleanup
    #   mwallraf.ekinops.oneos_acl_interfaces:
    #     config:
    #       - name: GigabitEthernet 0/3
    #     state: deleted

    # note: don't use overridden state unless you specify config
    #       for all existing interfaces
