# -*- coding: utf-8 -*-
# Copyright 2022 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function

__metaclass__ = type

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the
# cli_rm_builder.
#
# Manually editing this file is not advised.
#
# To update the argspec make the desired changes
# in the module docstring and re-run
# cli_rm_builder.
#
#############################################

"""
The arg spec for the oneos_acls module
"""


class AclsArgs(object):  # pylint: disable=R0903
    """The arg spec for the oneos_acls module
    """

    argument_spec = {
        "config": {
            "type": "list",
            "elements": "dict",
            "options": {
                "afi": {
                    "required": True,
                    "type": "str",
                    "choices": ["ipv4", "ipv6"],
                },
                "acls": {
                    "type": "list",
                    "elements": "dict",
                    "options": {
                        "name": {"type": "str", "required": True},
                        "acl_type": {
                            "type": "str",
                            "choices": ["extended", "standard", "remark"],
                        },
                        "aces": {
                            "mutually_exclusive": [["name"], ["number"]],
                            "elements": "dict",
                            "type": "list",
                            "options": {
                                "grant": {"type": "str"},
                                "protocol_options": {
                                    "type": "dict",
                                    "options": {
                                        "protocol": {"type": "str"},
                                        "protocol_number": {"type": "int"},
                                        "icmp_message_type": {"type": "int"},
                                        "icmp_message_code": {"type": "int"},
                                    },
                                },
                                "remarks": {"type": "list", "elements": "str"},
                                "sequence": {"type": "int"},
                                "source": {
                                    "type": "dict",
                                    "mutually_exclusive": [
                                        ["address", "any"],
                                        ["wildcard_bits", "any"],
                                    ],
                                    "required_together": [
                                        "address",
                                        "wildcard_bits",
                                    ],
                                    "options": {
                                        "host": {"type": "str"},
                                        "address": {"type": "str"},
                                        "wildcard_bits": {"type": "str"},
                                        "any": {"type": "bool"},
                                        "port_protocol": {
                                            "type": "dict",
                                            "options": {
                                                "eq": {"type": "str"},
                                                "range": {
                                                    "type": "dict",
                                                    "options": {
                                                        "start": {"type": "int"},
                                                        "end": {"type": "int"},
                                                    },
                                                },
                                            },
                                        },
                                    },
                                },
                                "destination": {
                                    "mutually_exclusive": [
                                        ["address", "any"],
                                        ["wildcard_bits", "any"],
                                    ],
                                    "required_together": [
                                        "address",
                                        "wildcard_bits",
                                    ],
                                    "type": "dict",
                                    "options": {
                                        "host": {"type": "str"},
                                        "address": {"type": "str"},
                                        "wildcard_bits": {"type": "str"},
                                        "any": {"type": "bool"},
                                        "port_protocol": {
                                            "type": "dict",
                                            "options": {
                                                "eq": {"type": "str"},
                                                "range": {
                                                    "type": "dict",
                                                    "options": {
                                                        "start": {"type": "int"},
                                                        "end": {"type": "int"},
                                                    },
                                                },
                                            },
                                        },
                                    },
                                },
                                "dscp": {"type": "int"},
                                "fragments": {"type": "bool"},
                                "reflexive": {"type": "bool"},
                                "log": {"type": "bool"},
                                "option": {
                                    "type": "dict",
                                    "options": {
                                        "ip_option_value": {"type": "int"}
                                    },
                                },
                                "precedence": {"type": "int"},
                            },
                        },
                    },
                },
            },
        },
        "running_config": {"type": "str"},
        "state": {
            "type": "str",
            "choices": [
                "merged",
                "replaced",
                "overridden",
                "deleted",
                "gathered",
                "rendered",
                "parsed",
            ],
            "default": "merged",
        },
    }  # pylint: disable=C0301
